# Generated by Django 4.1 on 2022-09-20 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='투자원금')),
            ],
            options={
                'verbose_name': '투자정보',
                'verbose_name_plural': '투자정보',
                'db_table': 'account_basic_info',
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(verbose_name='계좌번호')),
                ('account_name', models.CharField(max_length=45, verbose_name='계좌명')),
                ('stock_firm', models.CharField(max_length=45, verbose_name='증권사')),
            ],
            options={
                'verbose_name': '계좌정보',
                'verbose_name_plural': '계좌정보',
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='AssetGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=45, verbose_name='종목명')),
                ('isin', models.CharField(max_length=45, verbose_name='ISIN')),
                ('group_category', models.CharField(max_length=45, verbose_name='자산그룹')),
            ],
            options={
                'verbose_name': '자산그룹정보',
                'verbose_name_plural': '자산그룹정보',
                'db_table': 'accset_group_info',
            },
        ),
        migrations.CreateModel(
            name='UserAssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='현재가')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유수량')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.assetgroupinfo', verbose_name='자산그룹정보')),
            ],
            options={
                'verbose_name': '고객자산정보',
                'verbose_name_plural': '고객자산정보',
                'db_table': 'user_accset_info',
            },
        ),
    ]
