# Generated by Django 4.1 on 2022-09-17 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=45, verbose_name='종목명')),
                ('isin', models.CharField(max_length=45, verbose_name='ISIN')),
                ('group_category', models.CharField(max_length=45, verbose_name='자산그룹')),
            ],
            options={
                'verbose_name': '자산그룹정보',
                'verbose_name_plural': '자산그룹정보',
                'db_table': 'accset_group_info',
            },
        ),
        migrations.CreateModel(
            name='UserAssetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='현재가')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='보유수량')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.assetgroupinfo', verbose_name='자산그룹정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='고객')),
            ],
            options={
                'verbose_name': '고객자산정보',
                'verbose_name_plural': '고객자산정보',
                'db_table': 'user_accset_info',
            },
        ),
    ]
