# Generated by Django 4.1 on 2022-09-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_alter_accountbasicinfo_user'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='고객'),
        ),
    ]
