# Generated by Django 4.1 on 2022-09-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('transfer_identifier', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(verbose_name='계좌번호')),
                ('user_name', models.CharField(max_length=45, verbose_name='고객명')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='거래금액')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '입금거래정보',
                'verbose_name_plural': '입금거래정보',
                'db_table': 'trade_info',
            },
        ),
    ]
