# Generated by Django 4.1 on 2022-09-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accountinfo_user_alter_accountbasicinfo_user'),
        ('investments', '0002_alter_userassetinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='고객'),
        ),
    ]
