# Generated by Django 4.1 on 2022-09-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_tradeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeinfo',
            old_name='transfer_identifier',
            new_name='id',
        ),
    ]
