# Generated by Django 4.1 on 2022-09-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='고객명')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(verbose_name='계좌번호')),
                ('account_name', models.CharField(max_length=45, verbose_name='계좌명')),
                ('stock_firm', models.CharField(max_length=45, verbose_name='증권사')),
                ('in_principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='투자원금')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='고객')),
            ],
            options={
                'verbose_name': '계좌정보',
                'verbose_name_plural': '계좌정보',
                'db_table': 'account_info',
            },
        ),
    ]
