# Generated by Django 4.1 on 2022-09-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_principal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='투자원금')),
            ],
            options={
                'verbose_name': '투자정보',
                'verbose_name_plural': '투자정보',
                'db_table': 'account__basic_info',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(default=1, max_length=45, verbose_name='계좌명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(default=1, verbose_name='계좌번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stock_firm',
            field=models.CharField(default=1, max_length=45, verbose_name='증권사'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.AddField(
            model_name='accountbasicinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='고객'),
        ),
    ]
