# Generated by Django 4.1 on 2022-09-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_alter_accountbasicinfo_user'),
        ('investments', '0002_alter_userassetinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
