# Generated by Django 4.1 on 2022-09-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinfo_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(verbose_name='계좌번호')),
                ('account_name', models.CharField(max_length=45, verbose_name='계좌명')),
                ('stock_firm', models.CharField(max_length=45, verbose_name='증권사')),
            ],
            options={
                'verbose_name': '계좌정보',
                'verbose_name_plural': '계좌정보',
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='고객이름')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.accountinfo', verbose_name='계좌정보')),
            ],
            options={
                'verbose_name': '고객정보',
                'verbose_name_plural': '고객정보',
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='accountbasicinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='고객'),
        ),
    ]
