# Generated by Django 4.1 on 2022-09-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_accountinfo_user_alter_accountbasicinfo_user'),
        ('investments', '0003_alter_userassetinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
